### ISSUE TITLE
Failing to analyze ioc graph

### ISSUE THREAD

**Issue by robinbernon** [Nashenas88/coi-actix-sample#2]
Thanks a lot for making this example project - it's been really useful so far, I like coi a lot! :)

I had a small issue with trying to create dot graphs - when running the #[cfg(feature = "debug")] code on this repo (freshly cloned with no changes) I get the following error:

```
error[E0053]: method `dependencies` has an incompatible type for trait
  --> src\postgres.rs:26:10
   |
26 | #[derive(Provide)]
   |          ^^^^^^^ expected `&[&'static str]`, found struct `std::vec::Vec`
   |
   = note: expected fn pointer `fn(&postgres::PostgresPoolProvider<T>) -> &'static [&'static str]`
              found fn pointer `fn(&postgres::PostgresPoolProvider<T>) -> std::vec::Vec<&'static str>`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0053`.
```

I was wandering whether there are some extra environmental setup you are using to compile this on your machine as this isn't working out the box for me?

**Comment by Nashenas88** [comment]
This is a bug a coi-derive. Working on a fix now.

**Comment by Nashenas88** [comment]
@robinbernon thanks for filing a bug! Please let me know if you run into any other issues. Also, if you have any ideas for improvement, feel free to file feature requests in coi and coi-actix-web as well.

**Comment by robinbernon** [comment]
Hi @Nashenas88, sorry for the delayed reply. Thanks a lot for fixing this - working well now 👍 
I might take you up on the offer for feature requests if this is still ok?
Many thanks :)

**Comment by Nashenas88** [comment]
Feature requests are very welcome. I have some ideas, but it's hard to narrow down a focus without many users. I'll be slow to respond likely within the next week (moving to a new place), but I'll aim to be responsive by late next week at the earliest.
